base:
  netherite: 32000
  emerald: 15000
  diamond: 2800
  gold: 120
  iron: 80
  copper: 12
  redstone: 20
  lapis: 20
  coal: 8
  quartz: 25
  glowstone: 15
  amethyst: 6

#
# ⚖ Influence générale du minerai
#

weight:
  netherite: 0.9
  emerald: 1.0
  diamond: 1.0
  gold: 0.9
  iron: 0.7
  copper: 0.6
  quartz: 0.6
  redstone: 0.5
  lapis: 0.5
  coal: 0.3
  amethyst: 0.6
  glowstone: 0.6

#
# 💥 Résistance aux variations
# plus le chiffre est grand = plus stable
#

impact:
  netherite: 45
  emerald: 55
  diamond: 65
  gold: 80
  iron: 95
  copper: 110
  quartz: 110
  redstone: 130
  lapis: 130
  coal: 180
  amethyst: 120
  glowstone: 120

#
# 📈 Activité économique
#

activity:
  netherite: 0.0008
  emerald: 0.0010
  diamond: 0.0012
  gold: 0.0018
  iron: 0.0022
  copper: 0.0030
  quartz: 0.0030
  redstone: 0.0040
  lapis: 0.0040
  coal: 0.0050
  amethyst: 0.0035
  glowstone: 0.0035

#
# 🌟 Rareté uniforme
#

rarity:
  netherite: 500
  emerald: 500
  diamond: 500
  gold: 500
  iron: 500
  copper: 500
  quartz: 500
  redstone: 500
  lapis: 500
  coal: 500
  amethyst: 500
  glowstone: 500

#
# ⚙ MOTEUR ÉCONOMIQUE
#

engine:

  #
  # 🔄 Retour progressif au prix base
  #

  base_return: 0.012

  #
  # 📉 Variation max par tick
  #

  max_change: 0.035

  #
  # 📊 Limite activité
  #

  activity_cap: 0.03

  #
  # 🧱 Limites prix
  #

  min_price_factor: 0.45
  max_price_factor: 1.35

  #
  # 🧹 Nettoyage stock
  #

  stock_decay: 0.90

  #
  # 🛒 Bonus achat
  #

  buy_multiplier: 1.35

  #
  # 💸 Vente normale
  #

  sell_multiplier: 1.0

  #
  # 🌟 Rareté globale légère
  #

  rarity:

    enabled: true

    #
    # légère tension économique
    #

    boost: 0.0005

    #
    # neutre
    #

    exponent: 1.00

    #
    # plafond raisonnable
    #

    max_boost: 0.008