base:
  netherite: 32000
  emerald: 15000
  diamond: 2800
  gold: 120
  iron: 80
  copper: 12
  redstone: 20
  lapis: 20
  coal: 8
  quartz: 25
  glowstone: 15
  amethyst: 6

#
# ⚖ Influence générale du minerai
#

weight:
  netherite: 0.9
  emerald: 1.0
  diamond: 1.0
  gold: 0.9
  iron: 0.7
  copper: 0.6
  quartz: 0.6
  redstone: 0.5
  lapis: 0.5
  coal: 0.3
  amethyst: 0.6
  glowstone: 0.6

#
# 💥 Résistance aux variations
# plus le chiffre est grand = plus stable
#

impact:
  netherite: 20
  emerald: 25
  diamond: 30
  gold: 55
  iron: 75
  copper: 95
  quartz: 90
  redstone: 110
  lapis: 110
  coal: 150
  amethyst: 100
  glowstone: 100

#
# 📈 Activité économique
#

activity:
  netherite: 0.0012
  emerald: 0.0015
  diamond: 0.0018
  gold: 0.0024
  iron: 0.0030
  copper: 0.0034
  quartz: 0.0030
  redstone: 0.0040
  lapis: 0.0040
  coal: 0.0050
  amethyst: 0.0035
  glowstone: 0.0035

#
# 🌟 Seuil rareté
#

rarity:
  netherite: 40
  emerald: 120
  diamond: 180
  gold: 300
  iron: 500
  copper: 700
  quartz: 600
  redstone: 900
  lapis: 900
  coal: 1400
  amethyst: 750
  glowstone: 750

#
# ⚙ MOTEUR ÉCONOMIQUE
#

engine:

  #
  # 🔄 Retour progressif au prix base
  #

  base_return: 0.012

  #
  # 📉 Variation max par tick
  #

  max_change: 0.035

  #
  # 📊 Limite activité
  #

  activity_cap: 0.03

  #
  # 🧱 Limites prix
  #

  min_price_factor: 0.45
  max_price_factor: 1.5

  #
  # 🧹 Nettoyage stock
  #

  stock_decay: 0.90

  #
  # 🛒 Bonus achat
  #

  buy_multiplier: 1.35

  #
  # 💸 Vente normale
  #

  sell_multiplier: 1.0

  #
  # 🌟 Rareté
  #

  rarity:
    enabled: true

    boost: 0.0010

    exponent: 1.05

    max_boost: 0.018

#
# 🌟 RÉGLAGES SPÉCIAUX
#

rarity_settings:

  netherite:
    boost: 0.0009
    exponent: 1.04
    max_boost: 0.015

  emerald:
    boost: 0.0010
    exponent: 1.06
    max_boost: 0.020

  diamond:
    boost: 0.0011
    exponent: 1.07
    max_boost: 0.022

  gold:
    boost: 0.0012
    exponent: 1.07
    max_boost: 0.024

  iron:
    boost: 0.0010
    exponent: 1.05
    max_boost: 0.020

  copper:
    boost: 0.0009
    exponent: 1.04
    max_boost: 0.018

  quartz:
    boost: 0.0009
    exponent: 1.04
    max_boost: 0.018

  redstone:
    boost: 0.0010
    exponent: 1.05
    max_boost: 0.020

  lapis:
    boost: 0.0010
    exponent: 1.05
    max_boost: 0.020

  coal:
    boost: 0.0006
    exponent: 1.02
    max_boost: 0.012

  amethyst:
    boost: 0.0009
    exponent: 1.04
    max_boost: 0.018

  glowstone:
    boost: 0.0009
    exponent: 1.04
    max_boost: 0.018