name: MoodCraftBridge
version: 1.0
main: fr.moodcraft.bridge.Main
api-version: 1.20

commands:
  ecoreload:
    description: Reload économie
  ecoreset:
    description: Reset économie
  iban:
    description: Voir son IBAN
    usage: /iban [joueur]
  ecotest:
    description: Test du marché
  prix:
    description: Ouvre la bourse